version: '3.4'

services:
  rplp.api:
    container_name: rplp.api
    image: revueparlespairs/rplpapi-dev
    build:
      context: .
      dockerfile: RPLP.API/Dockerfile
    ports: 
      - "47001:80"

  rplp.mvc:
    container_name: rplp.mvc
    image: revueparlespairs/rplpmvc-dev
    build:
      context: .
      dockerfile: RPLP.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
      - "443:443"


  rplp.db:
    container_name: rplp.db
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"
    volumes:
        - rplpvolume:/var/opt/mssql/data

  rplp.db.test:
    container_name: rplp.db.test
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"

volumes: 
    rplpvolume:
        name: "rplpvolume"