version: '3.4'

services:
  rplp.api:
    image: revueparlespairs/rplpapi
    build:
      context: .
      dockerfile: RPLP.API/Dockerfile
    ports: 
      - "47001:80"

  rplp.mvc:
    image: revueparlespairs/rplpmvc
    build:
      context: .
      dockerfile: RPLP.MVC/Dockerfile
    ports: 
      - "47002:80"

  rplp.db:
    container_name: rplp.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"
    volumes:
        - rplpvolume:/testfolder

volumes: 
    rplpvolume:
        name: "rplpvolume"