version: '3.4'

services:
  rplp.api:
    image: ${DOCKER_REGISTRY-}rplpapi
    build:
      context: .
      dockerfile: RPLP.API/Dockerfile

  rplp.mvc:
    image: ${DOCKER_REGISTRY-}rplpmvc
    build:
      context: .
      dockerfile: RPLP.MVC/Dockerfile
   
  rplp.db:
    container_name: rplp.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"
