version: '3.4'

services:
  rplp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "47001:80"

  rplp.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Cad3pend86!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "./%USERPROFILE%/.aspnet/https:/https:ro"
    command: bash -c 'dotnet dev-certs https --clean && dotnet dev-certs https --trust -ep "./%USERPROFILE%/.aspnet/https/aspnetapp.pfx"'
    ports:
      - "80:80"
      - "443:443"

