version: '3.4'

services:
  rplp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  rplp.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

