version: '3.4'

services:
  rplp.api:
    container_name: rplp.api
    image: revueparlespairs/rplpapi-dev
    build:
      context: .
      dockerfile: RPLP.API/Dockerfile
    ports:
      - "47001:80"
    depends_on:
      - rplp.db
    restart: always

  rplp.mvc:
    container_name: rplp.mvc
    image: revueparlespairs/rplpmvc-dev
    build:
      context: .
      dockerfile: RPLP.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password="aspnetmvc"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/data/https/localhost.pfx
    ports:
      - "80:80"
      - "443:443"
    restart: always

  rplp.coherencechecker:
    container_name: rplp.coherencechecker
    image: revueparlespairs/rplp-coherencechecker
    build:
      context: .
      dockerfile: RPLP.COHERENCECHECKER/Dockerfile
    depends_on:
      - rplp.db
    restart: always

  rplp.journalisation:
    container_name: rplp.journalisation
    image: revueparlespairs/rplp-journalisation
    build:
      context: .
      dockerfile: RPLP.JOURNALISATION/Dockerfile
    volumes:
      - rplpvolume_logs:/var/log/rplp/
    restart: always

  rplp.db:
    container_name: rplp.db
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"
    volumes:
      - rplpvolume:/var/opt/mssql/data
    restart: always

  rplp.db.test:
    container_name: rplp.db.test
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"

  rplp.rabbitmq:
    container_name: rplp.rabbitmq
    image: rabbitmq:3-management
    hostname: rplp.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  rplpvolume:
    name: "rplpvolume"
  rplpvolume_logs:
    name: "rplpvolume_logs"
