version: '3.9'

services:
  rplp.api:
    container_name: rplp.api
    image: revueparlespairs/rplpapi-dev:latest
    build:
      context: .
      dockerfile: RPLP.API/Dockerfile
    ports:
      - "47001:80"
    depends_on:
      rplp.db:
        condition: service_healthy
    restart: always

  rplp.mvc:
    container_name: rplp.mvc
    image: revueparlespairs/rplpmvc-dev:latest
    build:
      context: .
      dockerfile: RPLP.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password="aspnetmvc"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/data/https/localhost.pfx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rplp.journalisation
    volumes:
      - rplpvolume_logs:/var/log/rplp/
    restart: always

  rplp.coherencechecker:
    container_name: rplp.coherencechecker
    image: revueparlespairs/rplp-coherencechecker:latest
    build:
      context: .
      dockerfile: RPLP.COHERENCECHECKER/Dockerfile
    depends_on:
      rplp.db:
        condition: service_healthy
      rplp.rabbitmq:
        condition: service_healthy
    links: 
      - rplp.rabbitmq
    restart: always

  rplp.journalisation:
    container_name: rplp.journalisation
    image: revueparlespairs/rplp-journalisation:latest
    build:
      context: .
      dockerfile: RPLP.JOURNALISATION/Dockerfile
    depends_on:
      rplp.rabbitmq:
        condition: service_healthy
    links: 
      - rplp.rabbitmq
    volumes:
      - rplpvolume_logs:/var/log/rplp/
      - rplpvolume_logs_zip:/var/log/zip_rplp/
    restart: always

  rplp.validations:
    container_name: rplp.validations
    image: revueparlespairs/rplp-validations:latest
    build:
      context: .
      dockerfile: RPLP.VALIDATIONS/Dockerfile
    depends_on:
      rplp.rabbitmq:
        condition: service_healthy
    links: 
      - rplp.rabbitmq
    restart: always

  rplp.db:
    container_name: rplp.db
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Cad3pend86!", "-Q", "select 1", "-b", "-o", "/dev/null"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - rplpvolume:/var/opt/mssql/data
#      - C:\mssql:/tmp
#      - /home/rplp/data:/tmp
    restart: always

  rplp.db.test:
    container_name: rplp.db.test
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Cad3pend86!"
      ACCEPT_EULA: "Y"

  rplp.rabbitmq:
    container_name: rplp.rabbitmq
    image: rabbitmq:3-management
    hostname: rplp.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - rplpvolume_rabbitmq:/var/lib/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 2
    restart: always

volumes:
  rplpvolume:
    name: "rplpvolume"
  rplpvolume_logs:
    name: "rplpvolume_logs"
  rplpvolume_logs_zip:
    name: "rplpvolume_logs_zip"
  rplpvolume_rabbitmq:
    name: "rplpvolume_rabbitmq"